//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyawoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEDUCATION
    {
        public int SchoolId { get; set; }
        public string SchoolName { get; set; }
        public string SchollCity { get; set; }
        public string SchollStatus { get; set; }
        public Nullable<byte> SchoolPoint { get; set; }
    }
}
